# action.yml
name: 'Generate Angular API packages'
description: 'This will generate Angular API packages based on OpenApi.yaml and push them to an other repo'
inputs:
  location-of-openapi-yaml:  # id of input
    description: 'The location of where the openapi is located'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.location-of-openapi-yaml }}